spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/ddukdoc
    username: ddukdoc
    password: ddukdoc108
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.ssafy.ddukdoc: DEBUG
    com.ssafy.ddukdoc.global.config.WebClientConfig: DEBUG
    com.zaxxer.hikari: TRACE

oauth:
  kakao:
    redirect-uri: http://localhost:8080/api/oauth/kakao/login
  ssafy:
    redirect-uri: http://localhost:8080/api/oauth/ssafy/login

app:
  domain:
    url: http://localhost:5173
    cors-origins: http://localhost:5173
  is-local: true
  cookie-domain: localhost