spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: redis-dev # 이후 ip주소로 변경

logging.level:
  org.hibernate.SQL: info

oauth:
  kakao:
    redirect-uri: https://ddukdoc.shop/api/oauth/kakao/login
  ssafy:
    redirect-uri: https://ddukdoc.shop/api/oauth/ssafy/login

app:
  domain: https://ddukdoc.shop
  is-local: false
  cookie-domain: ddukdoc.shop