spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging.level:
  org.hibernate.SQL: info