spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/ddukdoc
    username: ddukdoc
    password: ddukdoc108
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost


logging.level:
  org.hibernate.SQL: info

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE